### ISSUE TITLE
Error when deploying operationBefore or operationAfter hooks

### ISSUE THREAD

**Issue by richardkall** [graphcool/graphcool#818]
**What is the current behavior?**
Error when deploying: 

```
There are issues with the new service definition:

  Global
    ✖ unhandled error: File with path 'src/validateEmail.js' does not exist
```
**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

Functions part of `graphcool.yml`:
```
functions:
  hello:
    handler:
      code: src/hello.js
    type: resolver
    schema: src/hello.graphql
  validateEmail:
    type: operationBefore
    operation: User.create
    handler:
      code: src/validateEmail.js
```

Reproducible in this minimal sample project:
https://github.com/richardkall/graphcool-hook-issue

---
Using `graphcool/0.7.0 (darwin-x64) node-v8.5.0`

**Comment by mwickett** [comment]
I'm also seeing this issue as described.

**Comment by marktani** [comment]
This is fixed in the latest `@alpha` version and will be released to `@next` in 0.8.

**Comment by antho1404** [comment]
any idea when the 0.8 will be released ?

**Comment by marktani** [comment]
You can follow along the milestones here: https://github.com/graphcool/graphcool/milestones 🙂

**Comment by do4gr** [comment]
@antho1404 Since this was a backend change and that is already rolled it should be working now as intended. No need to wait for the next CLI release. I'm therefore closing the issue. Please report back if the issue still persists.

**Comment by antho1404** [comment]
This is actually working if deployed on graphcool but when deploying on the local environment the error persists (even with the last image with `gc local pull`) but it's ok for local development just have to wait few days
